config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "/", path_names: {sign_in: "login"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "pages#home", as: "root"
  
  resources :listings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :listing #here we don't add dependent: : destroy, it's because we don't want some one to stupidly delete our breeds.
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :breed
  enum sex:{female: 0, male: 1}
  validates :title, :breed_id, :sex, :price, :deposit, :date_of_birth, presence: true # presence is the validation rule, we didnt put :diet here, this means that the users do not necessarily input diet value
  has_one_attached :picture
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show]
  before_action :set_listing, only: [:show,:edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :set_breeds_and_sexes, only: [:new, :edit]
  def index
    #show all listings
    @listings = Listing.all
  end

  def show 
    #view a single listing
  end 

  def create
    # create new listing
    @listing = current_user.listings.create(listing_params)
    # byebug
    if @listing.errors.any?
      set_breeds_and_sexes
      render "new"
    else
      redirect_to listings_path
    end
    
  end

  def update
    #updates the current listing
  end

  def edit

    #shows the edit forms
  end

  def destroy
    #deletes current listing
  end

  def new
    #shows forms for creating a new listing
    @listing = Listing.new
  end


  private

  def set_breeds_and_sexes
    @breeds = Breed.all
    @sexes = Listing.sexes.keys
  end

  def set_listing
    id = params[:id]
    @listing = Listing.find(id)
  end

 def set_user_listing
  #method 1
  # @listing = Listing.where(user_id: current_user.id, id: params[:id]).first
  # if !@listing
  #   redirect_to listings_path 
  # end

 end

  #method 2
 def authorize_user
  if @listing.user_id != current_user.id
    redirect_to listings_path
  end
 end

  def listing_params
    params.require(:listing).permit(:title, :description, :breed_id, :sex, :price, :deposit, :date_of_birth, :diet, :picture )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GarretSnakeListing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= link_to "logout", destroy_user_session_path, method: "DELETE" if user_signed_in? %>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<% if listing.errors.any? %>
    <% listing.errors.full_messages.each do |error| %>
        <p><%= error %></p>
        <% end %>
<% end %>

<%= form_with model: listing, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price, min: 0 %>
  </div>

  <div>
    <%= form.label :deposit %>
    <%= form.number_field :deposit, min: 0 %>
  </div>

  <div>
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth, min: 0 %>
  </div>

  <div>
    <%= form.label :diet %>
    <%= form.text_field :diet %>
  </div>

  <div>
    <%= form.label :breed_id %>
    <%= form.select(:breed_id, @breeds.map {|b| [b.name, b.id] }) %>  
  </div>

  <div>

    <% @sexes.each do |option| %>
      <div>
        <%= form.radio_button :sex, option %>
        <%= form.label "sex_#{option}".to_sym, option%>
      </div>
    <% end %>

  </div>

  <div>
    <%= form.label :picture %>
    <%= form.file_field :picture, accept: 'image/png, image/jgp, image/jpeg' %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>
<%= render "form", listing: @listing, breeds: @breeds, sexes: @sexes %>

app/views/listings/index.html.erb
<h1>Snake Listings</h1>

<% @listings.each do |listing| %>
  <div class="card">
    <%= image_tag listing.picture if listing.picture.attached? %>
    <p><%= listing.title %></p>
    <p><%= listing.description %></p>
    <p><%= listing.breed.name %></p>
    <%= link_to "edit", edit_listing_path(listing.id) %>
    <%= link_to "show", listing_path(listing.id) %>
  </div>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render "form", listing: @listing, breeds: @breeds, sexes: @sexes %>

app/views/listings/show.html.erb
<h1><%= @listing.title %></h1>

<button>Pay Deposit $<%= number_with_precision(@listing.deposit / 100.0, precision: 2) %></button>

app/views/pages/home.html.erb
<h1>Legless Pets</h1>
  <%# <%= image_tag "hero.jpg" %> 
  <div class="hero"> </div>

<div>Find your dream snake</div>